pieces-app/documentation

- README.md
Need more work & links out to plugins resource centers.
> Added Main Repo Readme

- docs/our-community.mdx
All tasks should be outlined on the attached issue.
https://github.com/pieces-app/marketing/issues/35
> Community updates 

- docs/faq.mdx
connected to error caught by @mason-at-pieces 
https://github.com/pieces-app/documentation/issues/21
> Typo Updated 

- docs.json
- docs/extensions-plugins-support/troubleshooting-chrome.mdx
- docs/extensions-plugins-support/troubleshooting-edge.mdx
- docs/extensions-plugins-support/troubleshooting-jetbrains.mdx
- docs/extensions-plugins-support/troubleshooting-vscode.mdx
> Configuration for buttons on all of the plugins page based off chrome

- docs.json
Adding the sidebar link to installation page
> Pieces for Developers Download rework + addition on sidebar

- docs/extensions-plugins/chrome.mdx
- docs/extensions-plugins/edge.mdx
- docs/extensions-plugins/jetbrains.mdx
- docs/extensions-plugins/jupyterlab.mdx
- docs/extensions-plugins/teams.mdx
- docs/extensions-plugins/vscode.mdx
- docs/index.mdx
- docs/installation-getting-started/linux.mdx
- docs/installation-getting-started/macos.mdx
- docs/installation-getting-started/windows.mdx
More Updates to this index section from mason on an issue attached: 
https://github.com/pieces-app/documentation/issues/65
> Updated Plugin Section 

- docs/extensions-plugins/chrome.mdx
- docs/extensions-plugins/edge.mdx
- docs/extensions-plugins/jetbrains.mdx
- docs/extensions-plugins/jupyterlab.mdx
- docs/extensions-plugins/obsidian.mdx
- docs/extensions-plugins/teams.mdx
- docs/extensions-plugins/vscode.mdx
quick patch to add some links to the footer of each plugin page and clean some of the odd pieces.app links that were added.
> Updated footers on plugin page

- docs/features/pieces-copilot.mdx
- docs/features/user-settings.mdx
@georgia-at-pieces would also be great if you could go through some of these for grammatical adjustments as well if you haven't already. There were a few spots where I wasn't sure.
> Copy Edits & Typo Fixes

- docs.json
- docs/features/keyboard-shortcuts.mdx
- docs/index.mdx
- docs/product-highlights-and-benefits/collections.mdx
> Patches & Updates for July

- .idea/workspace.xml
- docs/extensions-plugins/jupyterlab.mdx
Redesigned the installation block using Accordion tag , check out the preview here : https://docs.pieces.app/~103/extensions-plugins/jupyterlab 
Tried to somehow add some space between the two Accordion but couldn't.
> Jupyter installation format

- .idea/workspace.xml
- docs/product-highlights-and-benefits/privacy-security-data.mdx
Need to updated privacy page with info on linux/windows file locations and want to get search hooked up based on the docs.
> Security Page - paths updated for linux + Search 

- docs/extensions-plugins/jetbrains.mdx
> Feat: Jetbrains documents

- .idea/workspace.xml
- docs.json
Testing out emojis in the sidebar headers to give a little flair! We will see how it looks and if it works.
> Adding Emojis to the Sidebar 

- .idea/workspace.xml
- docs.json
- docs/extensions-plugins/chrome.mdx
- docs/extensions-plugins/edge.mdx
- docs/extensions-plugins/jetbrains.mdx
- docs/extensions-plugins/jupyterlab.mdx
- docs/extensions-plugins/vscode.mdx
- docs/features/global-search.mdx
- docs/features/search-modes.mdx
- docs/installation-getting-started/linux.mdx
- docs/installation-getting-started/macos.mdx
- docs/installation-getting-started/what-am-i-installing.mdx
- docs/installation-getting-started/windows.mdx
> New Page - 'Search Modes' + Patches

- docs/extensions-plugins/edge.mdx
- docs/installation-getting-started/linux.mdx
1. Removed `$` symbol 
2. Added missing shell for commands
> docs: fix linux commands page

- docs/partnership-collection/dart-tutorial.mdx
- documentation.iml
3 new pages that need to be created for this partnership :0
> Dart tutorial updates

- docs/our-community.mdx
- added open source section here 
- update to feedback from link 
- copy updates throughout 
- update to product review section and links to marketplace 
- youtube embeds and youtube shorts added 
- buy us a coffee section added 
- learn something new section updated
> All changes from #cole for november community page upgrade

- docs.json
- docs/extensions-plugins/chrome.mdx
- docs/extensions-plugins/firefox.mdx
This is the new Firefox page, just included more info here and there specific to firefox, reused the images for the menu from chrome but will have to update these images for both Chrome and Firefox soon.
> New page addition for Mozilla Firefox Extension

- docs/extensions-plugins/chrome.mdx
added gif here and made sure that the rest of the page is looking alright :)
> chrome copilot .gif added

- docs.json
> Update to feedback support link

- README.md
Removed the extra "$" from the codeblock. 
Issue: #289
> fix: Codeblocks in Readme

- docs/extensions-plugins/azure-data-studio.mdx
- docs/extensions-plugins/jupyterlab.mdx
- docs/extensions-plugins/teams.mdx
- docs/extensions-plugins/vscode.mdx
I updated the Pieces OS Version requirements to resolve #291
> Updated PiecesOS version requirements

- docs/features/pieces-copilot.mdx
added phi-2 info for local models
> Pieces Copilot docs update

- docs/sdks/index.mdx
Added Language icons to the table.
> feat: Improved SDK landing page

- docs/support.mdx
added link to FAQs in a new sentence below the cards
> Updated Support page with FAQs link

- docusaurus.config.ts
[The issue](https://github.com/pieces-app/documentation/issues/315)
> Feat: issue #315

- docs/resources/live-context.mdx
Preview Link: https://documentation-git-live-context-res-c6cfab-pieces-for-developers.vercel.app/resources/live-context
> docs: Add Live Context reference guide

- docs/extensions-plugins/jetbrains.mdx
- docs/extensions-plugins/obsidian.mdx
- docs/extensions-plugins/vscode.mdx
- src/components/CTAButton/index.tsx
- src/components/Video/index.tsx
Updated pages:
- https://documentation-git-adding-youtube-embeds-pieces-for-developers.vercel.app/extensions-plugins/obsidian
- https://documentation-git-adding-youtube-embeds-pieces-for-developers.vercel.app/extensions-plugins/jetbrains
- https://documentation-git-adding-youtube-embeds-pieces-for-developers.vercel.app/extensions-plugins/vscode
@tsavo-at-pieces Also removed embeds from all embedded yt videos on the docs site 👍
> Adding youtube embeds

- docs/index.mdx
- pnpm-lock.yaml
- src/components/Video/index.tsx
on the home page of the docs there is a flicker that is caused by the video not being fully loaded on the first page render
adding an optional 'aspect ratio' parameter to the video component fixes this.
> feat: fix flicker

- docs/index.mdx
> fix: aspect ratio

- docs/features/power-menu.mdx
- src/components/Video/index.tsx
Preview Link: https://documentation-git-power-menu-patch-pieces-for-developers.vercel.app/features/power-menu
> docs: Comment out pending gifs in power menu doc

- definitions.json
- docs/build/glossary/GlossaryFilter.tsx
- docs/build/glossary/definitions.json
- docs/build/glossary/terms/link-time-optimization.md
- docs/build/glossary/terms/lora-fine-tuning.md
- docs/build/glossary/terms/vector-store.md
- docs/build/glossary/terms/zero-short-learning.md
Add new glossary terms: 
- Zero Shot Learning
- LORA
- Link Time optimization
- Vector Store
> feat(docs): add new glossary terms

- docs/resources/live-context.mdx
#481 
added new examples/prompts based on the blog post.
> feat(docs): Add new prompts for live context

- docs/features/pieces-copilot.mdx
Updates the LLM list, and tidies it up.
> Tidied and updated LLM list

- docs/extensions-plugins/obsidian.mdx
added banner, image alt text & links to launch new obsidian documentation
> launch_v2_obsidian_docs
