pieces-app/documentation

README.md
docs.json
docs/features/auto-enrichment.mdx
docs/features/creation-and-generation.mdx
docs/features/global-search.mdx
docs/features/managing-saved-materials.mdx
docs/features/one-click-snippet-sharing.mdx
docs/features/transforming-snippets.mdx
docs/global-search-suggestion-reuse/adjusting-settings-for-search.mdx
docs/global-search-suggestion-reuse/global-search.mdx
docs/global-search-suggestion-reuse/sort-scope-relevant.mdx
docs/global-search-suggestion-reuse/workflow-activity-stream.mdx
docs/global-search-suggestion-reuse/workflow-activity.mdx
docs/new-to-pieces/how-our-search-works.mdx
docs/personalized-link-sharing/saving-for-offline.mdx
docs/personalized-link-sharing/share-via-github-gist.mdx
docs/personalized-link-sharing/single-click-link-sharing.mdx
docs/product-highlights-and-benefits/import-gists-from-github.mdx
docs/product-highlights-and-benefits/in-project-snippet-discovery.mdx
docs/product-highlights-and-benefits/saving-screenshots.mdx
docs/product-highlights-and-benefits/saving-useful-developer-materials.mdx

Here is the doc with the copy + idea work from @wes-at-pieces and @georgia-at-pieces, latest is **Second Pass Complete**: 
https://drive.google.com/drive/u/0/folders/171W8hcCFFavmPo2FGqif-ki_kr5CRslh
Running List Here with Details:
**Copy Upgrades (Existing Pages - Still Need to Double Check Georgias Upgrades):**
New Pages that need Created, but likely will be folded into a separate pr following this one:

Copy upgrades and Docs Improvements

---

docs.json

Just need to add a flag but concerned since this API info is not added into the docs.page site concerning insights but in the past a number of nonspecific settings that hold true in the base tools that docs.page system is built on, you can normally pass in what i am calling "generally accepted values" based on the 3rd parties documentation.
This is important for working on this repo as there are some cases where you can get around the lack of documentation by trying things like above, or where when you try and bypass the docs.page documentation it will crash the whole site and cause it to loose rendering. 
For example : 
Insights
-  [mentioned inside of the algolia search configuration](https://docsearch.algolia.com/docs/DocSearch-v3#sending-events) that you can set `insights: true` in …

Testing Insights for Algolia Search 

---

docs.json
docs/extensions-plugins/obsidian.mdx

closes https://github.com/pieces-app/documentation/issues/160
preview link: https://docs.pieces.app/~161/extensions-plugins/obsidian
- brand unification (Pieces for Developers Obsidian Plugin)
- remove incorrect information
- add sections to install instructions on pfd and pos
- adjust the getting started link

fix: adjust the obsidian docs page

---

docs/extensions-plugins/vscode.mdx

fixes the vscode search hotkey from command + k to command + option + p

chore: fix hotkey

---

docs/extensions-plugins/jetbrains.mdx

for managing issues with JCEF and Downgrading.
- added a section for helping users step through this process when needed to get up and running and use the copilot in a few specific android studio situations

added to the intellij/jetbrains extension page, improve instructions

---

docs/extensions-plugins/jetbrains.mdx

quick patch to correct some errors from the last PR #204

updates for jcef - typos: AA -> a and ending statement on android studio

---

docs/extensions-plugins/jupyterlab.mdx

removes the 'installation issues' section from the jupyterlab plugin

chore: revert jlab warning

---

docs/installation-getting-started/macos.mdx

Updating the minimum monterey version from 11 -> 12.0 and was testing something around pathing for the name of branches.

Update minimum supported macOS Monterey version

---

docs/extensions-plugins/azuredatastudio.mdx
docs/extensions-plugins/chrome.mdx
docs/extensions-plugins/edge.mdx
docs/extensions-plugins/firefox.mdx
docs/extensions-plugins/jetbrains.mdx
docs/extensions-plugins/jupyterlab.mdx
docs/extensions-plugins/obsidian.mdx
docs/extensions-plugins/teams.mdx
docs/extensions-plugins/vscode.mdx

This PR changes the title and links for the "help and support" section. It ensures that users know where to find help with Pieces. 
Closes #249 
Here are the sections I've worked on so far:
This is still a work in progress 
**Updates:** Done

docs: update help and support  links

---

.github/workflows/preview-link.yml
docs/dev/internal/testing/testing.mdx
docs/installation-getting-started/windows.mdx

Lots of changes will be bundled into this one PR around different sections in the repo. Will add to the todo list here as new information is discovered or learned about. Also will connect issues as each one is addressed.

Preview Link, No follow research, Expanding docs.page functionality 

---

docs/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance.mdx

This pull request aims to help clarify to our users when and how they should use the custom url feature in vscode
1. advise against NGROK (most users actually need this for things like dev containers which are on the same LAN so they really shouldn't use NGROK)
2. advise against using the feature. I have multiple sentry errors from people who think that this is their pieces cloud url... etc. I don't know if we need to rename the setting, but in general I am trying to make them really think about if they need to use this feature before they do.
3. we also need to ensure we are showing people the correct port(s) according to their OS
preview: https://docs.pieces.app/~257

fix: adjust docs page for custom url

---

docs/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance.mdx

This PR adds a link to Tailscale in the "Using the Custom URL Feature to Access a Remote Pieces OS Instance" tutorial. It'll help users gain a better understanding of what alternatives to use. 
Closes #400

docs: mention Tailscale as an alternative for connecting remote URLS

---

docs/installation-getting-started/pieces-os.mdx

Fixes #516
The `Download Pieces Desktop + Pieces OS together` link now directly redirects to https://docs.pieces.app/installation-getting-started/what-am-i-installing#pieces-desktop-app--pieces-os

(Fixed) Installation method redirect URL

---

docs/build/reference/typescript/index.mdx

fixes #536 
I updated the code snippet for creating a Pieces configuration with the "new" keyword because it gives an error without it.

Fix Typescript SDK code snippet

---

docs/extensions-plugins/cli/commands.mdx

Updated the documentation to correctly reflect the changes in the open command implementation 
- added the docs for the -e flag 
- added the section for editor configurations 
- added note to indicate deprecation of the previous implementation of the open command 
- completely resolves pieces-app/cli-agent#156
- keeps the docs updated and inline with the readme of the updated version of the project.

Open command docs updation 

---

docs/extensions-plugins/neovim/quickstart.mdx

#562 
Previously the provided command could successfully work in only Windows and MacOS. I added the command for Debian/Ubuntu/(Ubuntu based distros) because python packages are globally installed differently in a Linux OS.  
My previous PR did not consider about Windows/MacOS, so changes were requested by @shivay-at-pieces. This is the new PR considering both Windows, MacOS and Debian based Linux Operating Systems.  
Hope it helps.

docs:fixed the pynvim installation command in quickstart

---

docs/extensions-plugins/jetbrains.mdx

Added a banner, links, new button and a CTA announcing the V2 JetBrains docs. Follows the same exact pattern as the current Sublime Text Docs that exists within the documentation repository.

announcing_v2_jetbrains_documentation

---

docs/extensions-plugins/sublime.mdx

replacing the out of date v2 sublime text documentation link with the current one

replacing_old_v2_sublime_text_link

---

docusaurus.config.ts

This change adds a Get Pieces link to the navbar so from any page when learning about Pieces it's easier to get to the install page with one click.

Adding get pieces to the navbar

---

docs/index.mdx
docs/installation-getting-started/linux.mdx
docs/installation-getting-started/macos.mdx
docs/installation-getting-started/pieces-os.mdx
docs/installation-getting-started/what-am-i-installing.mdx
docs/installation-getting-started/windows.mdx

adds new meet pieces CTA that links to windows, what am i installing, pieces os, macos and linux and main docs page
@tsavo-at-pieces

add_meet_pieces_CTA_to_6_pages

---

docs/installation-getting-started/pieces-os.mdx
docs/installation-getting-started/windows.mdx

Temporarily removes POS and PFD .EXE file download links for Windows devices on the Desktop App > Windows page & PiecesOS page.
@mark-at-pieces @nolan-at-pieces

remove_pos_pfd_exe_download_links

---

docs/installation-getting-started/pieces-os.mdx
docs/installation-getting-started/windows.mdx

Adds windows .exe download links for POS and PFD that were temporarily removed in a previous PR due to a bug that was resolved in the POS update to 11.1.1.

reinstate_temp_removed_pos_pfd_exe_dl_links

---

docs/installation-getting-started/macos.mdx
docs/installation-getting-started/pieces-os.mdx

Specifies more clearly the ARM / M-Series / Apple Silicon (from just ARM) copy for POS and PFD download links on PiecesOS and Desktop App documentation pages to make it more evident for users to download the right files for their architecture.

edit_arm_pos_pfd_dl_link_copy
